version: '3'
services:
  consul1:
    image: 'consul'
    hostname: 'consul1'
    networks:
      - consulnet
    command: "agent -server -bootstrap-expect=3 -ui -client=0.0.0.0"
  consul2:
    image: 'consul'
    hostname: 'consul2'
    links:
      - consul1
    networks:
      - consulnet
    command: "agent -server -bootstrap-expect=3 -retry-join consul1 -client=0.0.0.0"
  consul3:
    image: 'consul'
    hostname: 'consul3'
    networks:
      - consulnet
    links:
      - consul1
    command: "agent -server -bootstrap-expect=3 -retry-join consul1 -client=0.0.0.0"
