version: '3'
services:
  vault:
    build:
      context: ./vault
    image: vaultconsul
    cap_add:
      - IPC_LOCK
    ports:
      - '8200:8200'
      - "8500:8500"
    volumes:
      - ./data/vault:/tmp/vault
      - ./vault/config.hcl:/vault/config/config.hcl
      - ./vault/mysql/readonly_grant.sql:/vault/config/mysql/readonly_grant.sql
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      CONSUL_ADVERTISE_ADDR: "172.16.1.200"
    networks:
      consulnet:
        ipv4_address: 172.16.1.200
      vaultnet:
        ipv4_address: 172.16.2.10
    command: server
